In [32]:
import tensorflow as tf
import numpy as np
sess = tf.InteractiveSession()
print(tf.__version__)

1.12.0


/Users/01004106/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py:1702: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [13]:
x = np.random.randint(1,10,3*4).reshape(3,4)
y = np.random.randint(1,10,3*4).reshape(3,4)
print(x)
print(y)

[[7 4 1 8]
 [6 7 8 6]
 [7 5 2 1]]
[[3 3 9 3]
 [3 3 8 2]
 [1 7 5 6]]


In [14]:
xx = tf.constant(x)
print(xx)

Tensor("Const_2:0", shape=(3, 4), dtype=int64)


In [15]:
yy = tf.constant(x)
print(yy)

Tensor("Const_3:0", shape=(3, 4), dtype=int64)


In [16]:
print(xx + yy)

Tensor("add_4:0", shape=(3, 4), dtype=int64)


In [17]:
print(tf.add(xx, yy))

Tensor("Add_5:0", shape=(3, 4), dtype=int64)


In [20]:
print(sess)

In [21]:
sess.run(xx)

array([[7, 4, 1, 8],
       [6, 7, 8, 6],
       [7, 5, 2, 1]])

plusは、Tensorクラス。evalで評価される

In [28]:
plus = xx + yy
plus.eval()

array([[14,  8,  2, 16],
       [12, 14, 16, 12],
       [14, 10,  4,  2]])

runが使われるのはsession.run()の時、evalが使われるのはTensor.eval()の時、と覚えておけばよい・・・？