In [1]:
import numpy as np

In [9]:
x = [np.arange(3).reshape(1,3), np.arange(3,0,-1).reshape(1,3)]
x

[array([[0, 1, 2]]), array([[3, 2, 1]])]

In [12]:
np.argmax(x, axis=0)

array([[1, 1, 0]])

In [13]:
np.argmax(x, axis=1)

array([[0, 0, 0],
       [0, 0, 0]])

In [14]:
np.max(x, axis=1)

array([[0, 1, 2],
       [3, 2, 1]])

axis=1の方向には、長さ1しかない

In [15]:
np.argmax(x, axis=2)

array([[2],
       [0]])