In [4]:
import numpy as np
x = np.random.randn(3,3,3)
print(x)
print(np.max(x))

[[[ 0.36550043 -0.07088951 -1.12587035]
  [ 1.98586313 -0.86707343  0.79556648]
  [ 0.59956209  0.85068816 -1.52137006]]

 [[ 1.44870543  0.87819808  0.54857596]
  [-0.23008864 -0.5474654  -1.15850015]
  [ 0.39693414 -1.65029245 -0.90012156]]

 [[ 0.62143884 -0.51846933  1.08429336]
  [ 0.08429032 -1.28019155  1.00484004]
  [ 0.3919894   0.22888356 -1.72456011]]]
1.985863131991259
