In [3]:
import numpy as np

In [3]:
x = np.arange(4).reshape((-1,2))
print(x)

[[0 1]
 [2 3]]


In [4]:
a = np.arange(2)
print(a)

[0 1]


In [6]:
y = np.dot(x, a)
print(y)
print(y.shape)

[1 3]
(2,)


aは、縦ベクトルとみなされる。自然な挙動

いつも縦ベクトルとみなされると思っているとハマる例

In [12]:
z = np.random.randn(2,1)
print(z)
print(z.shape)

[[1.63649252]
 [0.81033067]]
(2, 1)


In [13]:
print(y+z)

[[2.63649252 4.63649252]
 [1.81033067 3.81033067]]


(2,)の形と(2,1)の形のベクトルを足すと、ブロードキャストのせいで変なことになる。

In [14]:
print(z+y)

[[2.63649252 4.63649252]
 [1.81033067 3.81033067]]


ブロードキャストの一般的なルールが分からないな・・・

# 軸方向にdotをかける

In [11]:
x = np.arange(2*3*4).reshape((2,3,4))
print(x)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [12]:
y = np.arange(2*10).reshape((10,2))
print(y)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [14]:
np.dot(x, y)

ValueError: shapes (2,3,4) and (10,2) not aligned: 4 (dim 2) != 10 (dim 0)

デフォルトでは、一番最後の軸 x 一番最初の軸 に沿って積和をとる。行列の積を考えると自然な定義。デフォルトでは、というか、軸を指定する方法はnp.dotには無いのでtensordotを使う。

https://docs.scipy.org/doc/numpy/reference/generated/numpy.tensordot.html#numpy.tensordot

In [19]:
z = np.tensordot(x, y, (0, 1))
print(z)

[[[ 12  36  60  84 108 132 156 180 204 228]
  [ 13  41  69  97 125 153 181 209 237 265]
  [ 14  46  78 110 142 174 206 238 270 302]
  [ 15  51  87 123 159 195 231 267 303 339]]

 [[ 16  56  96 136 176 216 256 296 336 376]
  [ 17  61 105 149 193 237 281 325 369 413]
  [ 18  66 114 162 210 258 306 354 402 450]
  [ 19  71 123 175 227 279 331 383 435 487]]

 [[ 20  76 132 188 244 300 356 412 468 524]
  [ 21  81 141 201 261 321 381 441 501 561]
  [ 22  86 150 214 278 342 406 470 534 598]
  [ 23  91 159 227 295 363 431 499 567 635]]]


In [20]:
print(z.shape)

(3, 4, 10)
