In [1]:
import numpy as np

x = np.array([1,2,3])

In [2]:
x.pop(0)

AttributeError: 'numpy.ndarray' object has no attribute 'pop'

numpyのarrayにはpopはない

In [3]:
np.delete(x, 0)

array([2, 3])

In [4]:
x

array([1, 2, 3])

In [5]:
x = np.arange(10)
y = np.arange(10, 20)
print(x)
print(y)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [6]:
np.hstack((x, y))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
a = np.vstack((x,y))
print(a)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [8]:
a[:,0]

array([ 0, 10])

## 横につなげる

In [14]:
x = np.arange(10).reshape((-1,2))
y = np.arange(10, 20).reshape((-1,2))
x, y

(array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]),
 array([[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]))

In [15]:
np.hstack((x, y))

array([[ 0,  1, 10, 11],
       [ 2,  3, 12, 13],
       [ 4,  5, 14, 15],
       [ 6,  7, 16, 17],
       [ 8,  9, 18, 19]])