In [2]:
import numpy as np
x = np.array([[1,2,3],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [4]:
np.apply_along_axis(np.sum, 0, x)

array([5, 7, 9])

In [5]:
np.apply_along_axis(np.sum, 1, x)

array([ 6, 15])

In [6]:
def f(arr, z=0):
    return np.sum(arr) + z

In [10]:
np.apply_along_axis(f, 0, x, 100)

array([105, 107, 109])

numpy版のapply。apply_along_axis(関数, 軸, 配列, その他の引数)
'軸'に指定した次元が動く（結果では、その次元は潰される）