# 等間隔の数列に対するパーセンタイル

In [9]:
import numpy as np

xs = np.arange(10)
np.percentile(xs, np.arange(100, step=10))

array([0. , 0.9, 1.8, 2.7, 3.6, 4.5, 5.4, 6.3, 7.2, 8.1])

In [10]:
np.percentile(xs, np.linspace(0, 100, 11))

array([0. , 0.9, 1.8, 2.7, 3.6, 4.5, 5.4, 6.3, 7.2, 8.1, 9. ])

# 重複のある配列に対するパーセンタイル

In [11]:
xs2 = [0,0,0,1,1,1]
np.percentile(xs2, np.linspace(0, 100, 11))

array([0. , 0. , 0. , 0. , 0. , 0.5, 1. , 1. , 1. , 1. , 1. ])

In [12]:
xs3 = [0,0,1,1,2,2,3,3,4,4,5,5]
np.percentile(xs3, np.linspace(0, 100, 11))

array([0. , 0.1, 1. , 1.3, 2. , 2.5, 3. , 3.7, 4. , 4.9, 5. ])

In [13]:
xs4 = [0,0,1,1,2,2,3,3,4,4,5,5,5,5,5,5,5,5,5,5,5,5,5,5]
np.percentile(xs4, np.linspace(0, 100, 11))

array([0. , 1. , 2. , 3. , 4.2, 5. , 5. , 5. , 5. , 5. , 5. ])

データの重複が考慮されている（単純に、最大値と最小値の間を等分しているわけではない）

# 結果の長さ

In [16]:
ps = np.linspace(0, 100, 11)
print(len(ps))
print(len(np.percentile(xs4, ps)))

11
11


第二引数と同じ長さ