In [1]:
import numpy as np

In [2]:
x = np.random.randn(3,3)

In [3]:
print(x)

[[-0.52300258 -0.9665125  -0.51508444]
 [ 1.46504742  1.35774671  0.9556658 ]
 [ 0.55646023 -0.88865311 -0.55548743]]


In [8]:
print(np.pad(x, ((1,2),(0,0)), "constant", constant_values=(1,2)))

[[ 1.          1.          1.        ]
 [-0.52300258 -0.9665125  -0.51508444]
 [ 1.46504742  1.35774671  0.9556658 ]
 [ 0.55646023 -0.88865311 -0.55548743]
 [ 2.          2.          2.        ]
 [ 2.          2.          2.        ]]


In [10]:
print(np.pad(x, ((1,0),(1,0)), "constant", constant_values=((1,0),(2,0))))

[[ 2.          1.          1.          1.        ]
 [ 2.         -0.52300258 -0.9665125  -0.51508444]
 [ 2.          1.46504742  1.35774671  0.9556658 ]
 [ 2.          0.55646023 -0.88865311 -0.55548743]]
