In [4]:
import numpy as np
x = np.random.randn(2,3,4)
print(x)
print(np.average(x))

[[[ 8.96223498e-01 -1.35172823e+00  9.00560771e-01 -5.68712228e-01]
  [-1.07189712e+00 -5.58557713e-01  6.16530437e-01  5.99582668e-01]
  [-1.06811246e+00  7.41180986e-01 -4.14372615e-04 -1.16513892e+00]]

 [[-2.89017624e-01  1.09436198e-01  1.93610925e+00 -1.74516059e+00]
  [-4.48094210e-01  1.52515410e+00  3.18480346e+00  1.47172248e+00]
  [ 7.07353876e-01 -2.00333833e+00  2.19711054e-01 -1.38384148e-01]]]
0.10415886879542184
