In [1]:
import numpy as np


In [2]:
x = np.random.randn(4,3)
print(x)

[[-0.05763469 -0.24650115 -0.40645413]
 [-1.41108221  1.72153212 -0.0189337 ]
 [ 0.78822193 -0.72756955 -0.57607007]
 [-0.28768517  0.97491186 -1.26942929]]


In [5]:
y = np.sum(x, axis=1, keepdims=True)
print(y)
print(y.shape)

[[-0.71058997]
 [ 0.29151621]
 [-0.51541769]
 [-0.5822026 ]]
(4, 1)


In [6]:
z = np.sum(x, axis=1, keepdims=False)
print(z)

[-0.71058997  0.29151621 -0.51541769 -0.5822026 ]


デフォルトはkeepdims=False

In [7]:
print(np.sum(x, axis=1))

[-0.71058997  0.29151621 -0.51541769 -0.5822026 ]


In [9]:
w = np.sum(x, axis=0, keepdims=True)
print(w)

[[-0.96818014  1.72237328 -2.27088719]]


axis=1
-> 1番目の添字を動かしたsumが得られる
-> デフォルトでは1番目の添字の次元は縮退する(keepdims=False)
-> 0番目の添字に関する次元が残る

In [10]:
x[0][0] + x[0][1] + x[0][2]

-0.71058997221322229

In [12]:
a1 = np.array(range(24)).reshape(2,3,4)
print(a1)
print(a1.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)


In [13]:
a2 = np.sum(a1, axis=0)
print(a2)
print(a2.shape)

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
(3, 4)


In [14]:
a3 = np.sum(a1, axis=(0,1))
print(a3)
print(a3.shape)

[60 66 72 78]
(4,)
