In [1]:
import numpy as np

ブロードキャストは、*1番最後の軸に沿って*展開される。

In [2]:
x = np.arange(2*3*4).reshape((2,3,4))
print(x)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [3]:
y = np.arange(10, 14)
print(y)

[10 11 12 13]


In [4]:
x + y

array([[[10, 12, 14, 16],
        [14, 16, 18, 20],
        [18, 20, 22, 24]],

       [[22, 24, 26, 28],
        [26, 28, 30, 32],
        [30, 32, 34, 36]]])

xの1番最後の軸 <tt>(:,:,\*)</tt> に沿って、yが展開される。

In [2]:
x = np.arange(12).reshape((3,4))
y = np.arange(3)

In [3]:
x * y

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [4]:
x.T * y

array([[ 0,  4, 16],
       [ 0,  5, 18],
       [ 0,  6, 20],
       [ 0,  7, 22]])

In [5]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
x.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

ブロードキャストは、「一番内側の軸に沿って配置される」ぽい？

In [8]:
x = np.arange(2*3*4).reshape(2,3,4)

In [10]:
x * y

ValueError: operands could not be broadcast together with shapes (2,3,4) (3,) 

In [11]:
y = np.arange(2)

In [12]:
x * y

ValueError: operands could not be broadcast together with shapes (2,3,4) (2,) 

長さが整数倍でもだめ

In [13]:
y = np.arange(3*4).reshape(3,4)

In [14]:
x*y

array([[[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121]],

       [[  0,  13,  28,  45],
        [ 64,  85, 108, 133],
        [160, 189, 220, 253]]])

In [16]:
print(x, "\n", y)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


高次のオーダーでも、後ろの次元から詰められる

次の例の理解が難しい

In [38]:
a = np.array([1,10])
print(a)
print(a.shape)

[ 1 10]
(2,)


In [39]:
b = np.arange(100,102).reshape(2,1)
print(b)
print(b.shape)

[[100]
 [101]]
(2, 1)


In [40]:
print(a+b)

[[101 110]
 [102 111]]


In [41]:
c = a.reshape(1,2)
print(c)
print(c.shape)

[[ 1 10]]
(1, 2)


In [42]:
print(b+c)

[[101 110]
 [102 111]]


[1 10]と、[[1 10]]で、同じブロードキャスト結果になる。