In [1]:
import numpy as np

In [7]:
num = 2 * 3 * 4 * 5
a1 = np.array(range(num))
print(a1)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]


In [8]:
a2 = a1.reshape(2,3,4,5)
print(a2)

[[[[  0   1   2   3   4]
   [  5   6   7   8   9]
   [ 10  11  12  13  14]
   [ 15  16  17  18  19]]

  [[ 20  21  22  23  24]
   [ 25  26  27  28  29]
   [ 30  31  32  33  34]
   [ 35  36  37  38  39]]

  [[ 40  41  42  43  44]
   [ 45  46  47  48  49]
   [ 50  51  52  53  54]
   [ 55  56  57  58  59]]]


 [[[ 60  61  62  63  64]
   [ 65  66  67  68  69]
   [ 70  71  72  73  74]
   [ 75  76  77  78  79]]

  [[ 80  81  82  83  84]
   [ 85  86  87  88  89]
   [ 90  91  92  93  94]
   [ 95  96  97  98  99]]

  [[100 101 102 103 104]
   [105 106 107 108 109]
   [110 111 112 113 114]
   [115 116 117 118 119]]]]


np.reshapeは、指定する次元の1つを-1にできる。-1を指定された次元は、残りの次元から自動で推測される

In [9]:
a3 = a1.reshape(2,3,4,-1)
print(a3)

[[[[  0   1   2   3   4]
   [  5   6   7   8   9]
   [ 10  11  12  13  14]
   [ 15  16  17  18  19]]

  [[ 20  21  22  23  24]
   [ 25  26  27  28  29]
   [ 30  31  32  33  34]
   [ 35  36  37  38  39]]

  [[ 40  41  42  43  44]
   [ 45  46  47  48  49]
   [ 50  51  52  53  54]
   [ 55  56  57  58  59]]]


 [[[ 60  61  62  63  64]
   [ 65  66  67  68  69]
   [ 70  71  72  73  74]
   [ 75  76  77  78  79]]

  [[ 80  81  82  83  84]
   [ 85  86  87  88  89]
   [ 90  91  92  93  94]
   [ 95  96  97  98  99]]

  [[100 101 102 103 104]
   [105 106 107 108 109]
   [110 111 112 113 114]
   [115 116 117 118 119]]]]


In [10]:
a4 = a1.reshape(2,3,-1,5)
print(a4)

[[[[  0   1   2   3   4]
   [  5   6   7   8   9]
   [ 10  11  12  13  14]
   [ 15  16  17  18  19]]

  [[ 20  21  22  23  24]
   [ 25  26  27  28  29]
   [ 30  31  32  33  34]
   [ 35  36  37  38  39]]

  [[ 40  41  42  43  44]
   [ 45  46  47  48  49]
   [ 50  51  52  53  54]
   [ 55  56  57  58  59]]]


 [[[ 60  61  62  63  64]
   [ 65  66  67  68  69]
   [ 70  71  72  73  74]
   [ 75  76  77  78  79]]

  [[ 80  81  82  83  84]
   [ 85  86  87  88  89]
   [ 90  91  92  93  94]
   [ 95  96  97  98  99]]

  [[100 101 102 103 104]
   [105 106 107 108 109]
   [110 111 112 113 114]
   [115 116 117 118 119]]]]


# reshape時の順番を検討

In [11]:
print(a2.reshape(5,4,3,-1))

[[[[  0   1]
   [  2   3]
   [  4   5]]

  [[  6   7]
   [  8   9]
   [ 10  11]]

  [[ 12  13]
   [ 14  15]
   [ 16  17]]

  [[ 18  19]
   [ 20  21]
   [ 22  23]]]


 [[[ 24  25]
   [ 26  27]
   [ 28  29]]

  [[ 30  31]
   [ 32  33]
   [ 34  35]]

  [[ 36  37]
   [ 38  39]
   [ 40  41]]

  [[ 42  43]
   [ 44  45]
   [ 46  47]]]


 [[[ 48  49]
   [ 50  51]
   [ 52  53]]

  [[ 54  55]
   [ 56  57]
   [ 58  59]]

  [[ 60  61]
   [ 62  63]
   [ 64  65]]

  [[ 66  67]
   [ 68  69]
   [ 70  71]]]


 [[[ 72  73]
   [ 74  75]
   [ 76  77]]

  [[ 78  79]
   [ 80  81]
   [ 82  83]]

  [[ 84  85]
   [ 86  87]
   [ 88  89]]

  [[ 90  91]
   [ 92  93]
   [ 94  95]]]


 [[[ 96  97]
   [ 98  99]
   [100 101]]

  [[102 103]
   [104 105]
   [106 107]]

  [[108 109]
   [110 111]
   [112 113]]

  [[114 115]
   [116 117]
   [118 119]]]]


### Q: reshapeしてから転置するのと、最初から転置した次元を指定したら同じ結果？

In [15]:
print(a2.reshape(2*3*4, -1).T)

[[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
   90  95 100 105 110 115]
 [  1   6  11  16  21  26  31  36  41  46  51  56  61  66  71  76  81  86
   91  96 101 106 111 116]
 [  2   7  12  17  22  27  32  37  42  47  52  57  62  67  72  77  82  87
   92  97 102 107 112 117]
 [  3   8  13  18  23  28  33  38  43  48  53  58  63  68  73  78  83  88
   93  98 103 108 113 118]
 [  4   9  14  19  24  29  34  39  44  49  54  59  64  69  74  79  84  89
   94  99 104 109 114 119]]


In [13]:
print(a2.reshape(-1, 2*3*4))

[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19  20  21  22  23]
 [ 24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41
   42  43  44  45  46  47]
 [ 48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65
   66  67  68  69  70  71]
 [ 72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
   90  91  92  93  94  95]
 [ 96  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111 112 113
  114 115 116 117 118 119]]


A: 違う