In [1]:
import numpy as np

== 2018-08-16 ==============================

In [2]:
list(range(1, 10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
print(10 // 2)
print(11 // 2)
print(12 // 2)

5
5
6


In [7]:
len({"a": 1, "b": 2})

2

In [8]:
"w" + 1

TypeError: Can't convert 'int' object to str implicitly

In [9]:
"w" + str(1)

'w1'

In [12]:
1 - np.ones(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [16]:
x = np.array([1,2,3,4,5,6]).reshape(2,3)
print(x)
np.sum(x, axis=1, keepdims=True)

[[1 2 3]
 [4 5 6]]


array([[ 6],
       [15]])

In [21]:
x = np.array(range(1, 7)).reshape(2,3)
print(np.divide(x, 3))
print(x / 3)

[[ 0.33333333  0.66666667  1.        ]
 [ 1.33333333  1.66666667  2.        ]]
[[ 0.33333333  0.66666667  1.        ]
 [ 1.33333333  1.66666667  2.        ]]


In [19]:
x

array([[1, 2, 3],
       [4, 5, 6]])

====== 2018-08-26 ======

In [4]:
np.array(range(10))**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [5]:
np.sqrt(2)

1.4142135623730951