In [6]:
import numpy as np

In [7]:
x = np.zeros((3,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
x[0,0] = 1
print(x)

[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [46]:
y = np.random.uniform(0,1,100).reshape((10,10))
print(y)

[[0.65282996 0.76733975 0.72793495 0.31328799 0.294968   0.10365011
  0.44458335 0.59861271 0.16408947 0.5396783 ]
 [0.30025675 0.56375171 0.0608622  0.35789066 0.00357428 0.1901732
  0.94380539 0.06408372 0.03203498 0.55702187]
 [0.9981593  0.69941894 0.30416144 0.93975869 0.63068713 0.94430634
  0.82836545 0.7784457  0.65804551 0.12643054]
 [0.841293   0.83511673 0.0081528  0.55321198 0.06757881 0.64350073
  0.13770738 0.66496117 0.09593662 0.32038807]
 [0.31939921 0.26803451 0.82423724 0.94962358 0.24207672 0.74613384
  0.40008108 0.57550371 0.32001559 0.31806883]
 [0.76822077 0.64452553 0.34092647 0.43673796 0.72998833 0.87380078
  0.66109857 0.73707145 0.42941846 0.62600554]
 [0.80953225 0.00439218 0.1600398  0.81509006 0.47838556 0.42297466
  0.95431253 0.93034098 0.335337   0.0200803 ]
 [0.75149668 0.21171173 0.59795688 0.94428646 0.90471029 0.7811154
  0.24237062 0.87910738 0.44162037 0.72502448]
 [0.60440192 0.94510044 0.88656389 0.10380169 0.16114201 0.4943358
  0.02418718 0.

In [47]:
y < 0.3

array([[False, False, False, False,  True,  True, False, False,  True,
        False],
       [False, False,  True, False,  True,  True, False,  True,  True,
        False],
       [False, False, False, False, False, False, False, False, False,
         True],
       [False, False,  True, False,  True, False,  True, False,  True,
        False],
       [False,  True, False, False,  True, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True, False, False, False, False, False, False,
         True],
       [False,  True, False, False, False, False,  True, False, False,
        False],
       [False, False, False,  True,  True, False,  True, False, False,
         True],
       [False, False,  True, False, False, False, False, False, False,
        False]])

In [51]:
len(x)

3

In [52]:
np.zeros_like(x)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [54]:
x.shape[0]

3

In [65]:
z = np\
  .random.uniform(0, 1, 9).reshape(x.shape)

In [66]:
x[:,1]

array([0., 0., 0.])

In [77]:
x1 = []
x1.append(1)
print(x1)

[1]


In [79]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [87]:
x2 = np.array(range(10))
print(x2)
max(x2[[1,3]])

[0 1 2 3 4 5 6 7 8 9]


3

In [88]:
True + True

2

In [5]:
x3 = np.array(range(10))
x4 = x3.copy()
x4[0] = 100
print(x3)
print(x4)

[0 1 2 3 4 5 6 7 8 9]
[100   1   2   3   4   5   6   7   8   9]


In [9]:
x5 = np.array(range(12)).reshape((3,4))
print(x5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [10]:
print("\n")