In [1]:
import numpy as np

x = np.array([1,2,3])

In [2]:
x.pop(0)

AttributeError: 'numpy.ndarray' object has no attribute 'pop'

numpyのarrayにはpopはない

In [4]:
np.delete(x, 0)

array([2, 3])

In [5]:
x

array([1, 2, 3])

In [7]:
x = np.arange(10)
y = np.arange(10, 20)
print(x)
print(y)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [9]:
np.hstack((x, y))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [12]:
a = np.vstack((x,y))
print(a)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [16]:
a[:,0]

array([ 0, 10])