In [1]:
import numpy as np
x = np.zeros((1,2,3))

In [2]:
print(x)

[[[0. 0. 0.]
  [0. 0. 0.]]]


In [5]:
y = x[0, 1]
y[:] = 1

In [6]:
print(y)

[1. 1. 1.]


In [7]:
print(x)

[[[0. 0. 0.]
  [1. 1. 1.]]]


部分配列を取得したら、参照が返ってくる。スライスした場合はどうなるか？

In [8]:
z = np.zeros((4,4))
print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
w = z[2:4, 2:4]
w[:,:] = 1
print(w)

[[1. 1.]
 [1. 1.]]


In [11]:
print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 1.]
 [0. 0. 1. 1.]]


スライスした場合も、参照が返ってくる