In [1]:
import numpy as np
import pandas as pd

In [4]:
dat = pd.DataFrame(dict(
    x=np.arange(3),
    y=np.arange(4,7)
))

In [6]:
dat

x  y
0  0  4
1  1  5
2  2  6

# DataFrameを行列に = values

In [5]:
dat.values

array([[0, 4],
       [1, 5],
       [2, 6]])

# Seriesを配列に = ravel()

In [7]:
dat.x.ravel()

array([0, 1, 2])

In [8]:
dat.x.values # こっちでも同じだった

array([0, 1, 2])