In [1]:
import numpy as np
import tensorflow as tf
sess = tf.Session()

/Users/01004106/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [28]:
m, nh, nw, nc = 1,2,3,4

In [36]:
x = np.array(list(range(m*nh*nw*nc))).reshape(m, nh, nw, nc)
print(x)

[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]

  [[12 13 14 15]
   [16 17 18 19]
   [20 21 22 23]]]]


各ポジションのindexをずらした時の対象セルの位置を確認
（ポジション上で1番右が、1番近くの移動に対応）

In [40]:
x[0,0,0,0], x[0,1,0,0], x[0,0,1,0]

(0, 12, 4)

In [38]:
y = tf.constant(x)
print(sess.run(y))

[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]

  [[12 13 14 15]
   [16 17 18 19]
   [20 21 22 23]]]]


In [39]:
z = tf.reshape(y, [1, -1, nc])
print(sess.run(z))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


2,3番目のindexを入れ替えてからreshape（courseraのneural style transferの課題ではこれが必要だった）

In [45]:
w = tf.reshape(tf.transpose(y, perm=[0,2,1,3]), [1, -1, nc])
print(sess.run(w))

[[[ 0  1  2  3]
  [12 13 14 15]
  [ 4  5  6  7]
  [16 17 18 19]
  [ 8  9 10 11]
  [20 21 22 23]]]


(1,nh,nw,nc)のテンソルを(nc,nh * nw)にreshape。↑のwの転地と同じ結果になってほしい

In [47]:
x1 = tf.reshape(tf.transpose(y, perm=[0,3,2,1]), [1, nc, -1])
print(sess.run(x1))

[[[ 0 12  4 16  8 20]
  [ 1 13  5 17  9 21]
  [ 2 14  6 18 10 22]
  [ 3 15  7 19 11 23]]]
